apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-logger-deployment
  labels:
    app: http-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-logger
  template:
    metadata:
      labels:
        app: http-logger
    spec:
      containers:
      - name: nginx
        image: quay.io/port/http-logger:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-logger
spec:
  selector:
    app: http-logger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080